
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Nov 05 20:23:25 BRT 2022
//----------------------------------------------------

package src.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TYPE_STRING = 14;
  public static final int IDENT = 7;
  public static final int CLOSE = 9;
  public static final int SUM = 16;
  public static final int MULTI = 18;
  public static final int END = 3;
  public static final int TYPE_CHAR = 13;
  public static final int WRITE = 5;
  public static final int NUM = 20;
  public static final int SUB = 17;
  public static final int EQUALS = 15;
  public static final int EOF = 0;
  public static final int PRINT = 4;
  public static final int error = 1;
  public static final int TYPE_FLOAT = 11;
  public static final int DIVID = 19;
  public static final int START = 2;
  public static final int TYPE_DECLARATION = 10;
  public static final int OPEN = 8;
  public static final int CLOSE_SEQUENCE = 6;
  public static final int TYPE_INTEGER = 12;
}

